### PR TITLE
Travis: Use latest stable JRuby

### PR DESCRIPTION
**Pull request by olleolleolle**
- Add JRuby 9.1.7.0 to the build matrix
- ~Remove the `pry` gem from the Gemfile of the specs' `test_project`~

I don't how you at Burt use Jarå in practice, but I'm curious to see if latest stable can be used to run the test suite.

**Update**: This change ran into a broken version (1.14.3) of Bundler being the current stable.

~In order to work towards a functioning build in master, we can hold back the Bundler to `1.13.7`.~

## Currently failing test:

```
  1) Jara when creating a self-contained JAR the archive includes the dependencies
     Failure/Error: jar_entries.grep(%r{META-INF/gem.home/paint-[^/]+/lib/paint.rb}).should_not be_empty
       expected `[].empty?` to return false, got true
     # ./spec/integration/jara_spec.rb:107:in `block in (root)'

```

### CODE REVIEW

**Comment by iconara** [comment]
Looks like you need to make some changes in the dependencies of the example application to make it possible to bundle in JRuby 9K.

**Comment by olleolleolle** [comment]
@iconara Thanks for the hint! I'll begin by unseating `pry` from that Gemfile. Here goes!

**Comment by olleolleolle** [comment]
Removing `pry` seems to get jruby-9.1.7.0 to the same compatibility as jruby-1.7.x.

**Comment by iconara** [comment]
I guess there's been some changes either in how Bundler works or something else since that code was written. We want to install a few different gems when testing so that we can see that things are packaged correctly – so while removing `pry` is good for debug, ideally it should be possible to package something that depends on `pry`.

**Comment by olleolleolle** [comment]
When I kept `pry` in, the errors I had (and were able to reproduce locally) were:

```
  12) Jara when creating a self-contained JAR from the working directory includes unstaged changes
      Failure/Error: fail %(Command `#{command}` failed with output: #{output})

      RuntimeError:
        Command `BUNDLE_GEMFILE=/var/folders/c3/chrhhctn30z1jhqstpp7bt480000gn/T/d20170123-40701-1d6c2ux/test_project/Gemfile BUNDLE_PATH=/Users/olle/opensource/jara/vendor/test_project/ruby/2.2.0 .bundle/bin/rake clean package:test` failed with output: Bundler::VersionConflict: Bundler could not find compatible versions for gem "ffi":
          In snapshot (Gemfile.lock):
            ffi (= 1.9.17) java

          In Gemfile:
            pry java was resolved to 0.10.4, which depends on
              spoon (~> 0.0) java was resolved to 0.0.6, which depends on
                ffi java

            pry java was resolved to 0.10.4, which depends on
              spoon (~> 0.0) java was resolved to 0.0.6, which depends on
                ffi

        Running `bundle update` will rebuild your snapshot from scratch, using only
        the gems in your Gemfile, which may resolve the conflict.

                    start at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/resolver.rb:207
                  resolve at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/resolver.rb:181
                  resolve at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/definition.rb:252
                    specs at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/definition.rb:176
                specs_for at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/definition.rb:235
          requested_specs at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/definition.rb:224
          requested_specs at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/runtime.rb:118
                    setup at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/runtime.rb:19
                    setup at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler.rb:100
                   (root) at /Users/olle/.rvm/gems/jruby-1.7.26/gems/bundler-1.14.2/lib/bundler/setup.rb:20
                  require at org/jruby/RubyKernel.java:1040
                   (root) at /Users/olle/.rvm/rubies/jruby-1.7.26/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
                   (root) at .bundle/bin/rake:15
```

Compare and contrast with: https://github.com/bundler/bundler/issues/5349#issuecomment-274522948 

Pretty near, huh!

**Pull request closed without merging**
